from flask import Flask, render_template, request

app = Flask(__name__)

dropdown_options = {
    'COUNTRY':[['Part of','P36'],
                ['image','P18'],
                ['inception','P571'],
                ['official name','P1448'],
                ['native label','P1705'],
                ['shortname','P1813'],
                ['pronunciation audio','P443'],
                ['ethnic group','P172'],
                ['religion or worldview' , 'P140'],
                ['IPA transcription' , 'P898'],
                ['participant in' ,'P1344'],
                ['life expectancy','P2250'],
                ['named after','P138'],
                ['demonym','P1549'],
                ['official language','P37'],
                ['anthem','P85'],
                ['culture','P2596'],
                ['motto','P1546'],
                ['motto text','P1451'],
                ['continent','P30'],
                ['country','P17'],
                ['capital','P36'],
                ['geoshape','P3896'],
                ['highest point','P610'],
                ['lowest point','P1589'],
                ['basic form of government','P122'],
                ['office held by head of state','P1906'],
                ['head of state','P35'],
                ['head of government','P6'],
                ['executive body','P208'],
                ['legislative body','P194'],
                ['highest judicial authority','P209'],
                ['central bank','P1304'],
                ['diplomatic relation','P530'],
                ['member of','P463'],
                ['public holiday','P832'],
                ['age of maturity','P2997'],
                ['population','P1082'],
                ['retirement age','P3001'],
                ['currency','P38'],
                ['median income','P3529'],
                ['owner of','P1830'],
                ['shares border with','P47'],
                ['driving side','P1622'],
                ['language used','P2936'],
                ['official website','P856']],
    'TAXON': [['subclass of','P279'],
              ['image','P18'],
              ['video','P10'],
              ['pronunciation audio','P443'],
              ['mass,P2067'],
              ['taxon name','P225'],
              ['taxon rank','P105'],
              ['parent taxon','P171'],
              ['taxon common name','P1843'],
              ['original combination','P1403'],
              ['longest observed lifespan','P4214'],
              ['gestation period','P3063'],
              ['bite force quotient','P3485'],
              ['IUCN conservation status','P141'],
              ['audio','P51'],
              ['taxon range map image','P181'],
              ['spoken text audio','P989'],
              ['3D model','P4896'],
              ['has quality','P1552'],
              ['main food source','P1034'],
              ['described by source','P1343'],
              ['produced sound','P4733'],
              ['litter size','P7725'],
              ['period of location','P7862'],
              ['sequenced genome URL','P6800'],
              ['unicode character','P487'],
              ['has part(s) of the class','P2670'],
              ['commons gallery','P935'],
              ['commons category','P373'],
              ['topics main category','P910'],
              ['category for the view of the item','P8989'],
              ['GND ID','P227'],
              ['Biolib taxon ID','P838'],
              ['BNCF thesaurus ID','P508'],
              ['Cataloque of Life ID','P10585'],
              ['CITES Speciest ID','P2040'],
              ['eBiodiversity ID','P6864'],
              ['Encyclopedia of Life ID','P830'],
              ['English Vikidia ID','P7829'],
              ['Golden ID','P7502'],
              ['Google News topics ID','P5337'],
              ['Quora topic ID','P3417']],
    '3DFILM': [['part of','P361:'],
               ['logo image','154'],
               ['image','P18'],
               ['title','P1476'],
               ['named after','P138'],
               ['derivative work','P4969'],
               ['part of the series','P179'],
               ['main subject','P921'],
               ['followed by','P156'],
               ['genre','P136'],
               ['performer','P175'],
               ['country of origin','P495'],
               ['original language of film or TV show','P364'],
               ['publication date','P577'],
               ['director','P57'],
               ['screen writer','P58'],
               ['cast member','P161'],
               ['executive producer','P1431'],
               ['film editor','P1040'],
               ['production designer','P2554'],
               ['composer','P86'],
               ['producer','P162'],
               ['production company','P272'],
               ['distribution by','P750'],
               ['spoken text audio','P989'],
               ['soundtrack release','P406'],
               ['narrative location','P840'],
               ['filming location','P915'],
               ['duration','P2047'],
               ['aspect radio(W:H)','P2061'],
               ['original film format','P3803'],
               ['color','P462'],
               ['review score','P444'],
               ['award received','P166'],
               ['nominated for','P1411'],
               ['box office','P2142'],
               ['cost','P2130'],
               ['takes place in fictional universe','P1434'],
               ['fabrication method','P2079'],
               ['distribution format','P437']],
    'FILM' :[['image','P18'],
             ['video','P10'],
             ['title','P1476'],
             ['publication date','P577'],
             ['original language of film','P364'],
             ['genre','P136'],
             ['director','P57'],
             ['cast member','P161'],
             ['director of photography','P344'],
             ['screen writer','P58'],
             ['producer','P162'],
             ['film editor','P1040'],
             ['narrative location','P840'],
             ['filming location','P915'],
             ['country of rigin','P495'],
             ['color','P462'],
             ['list of characters','P1881'],
             ['composer','P86'],
             ['voice actor','P725'],
             ['production company','P272'],
             ['cost','P2130'],
             ['box office','P2142'],
             ['narrator','P2438'],
             ['presented in','P5072'],
             ['sound track release','P406'],
             ['significant event','P793'],
             ['costume designer','P2554'],
             ['duration','P2047'],
             ['distributed by','P750'],
             ['sound designer','P5028']],
    'CITY' :[['subclass of','P279'],
              ['image','P18'],
              ['short name','P1813'],
              ['next lower rank','P3729'],
              ['studied by','P2579'],
              ['nighttime view','P3451'],
              ['icon','P2910'],
              ['geography of topic ','P2633'],
              ['history of topic','P2184'],
              ['inception','P571'],
              ['official name','P1448'],
              ['native label','P1705'],
              ['nickname','P1449'],
              ['IPA transcription','P898'],
              ['named after','P138'],
             ['demonym','P1549'],
             ['official language','P37'],
             ['continent','P30'],
             ['country','P17'],
             ['capital of','P1376'],
             ['coordinates of easternmost point','P1334'],
             ['coordinates of northernmost point','P1332'],
             ['coordinates of southernmost point','P1333'],
             ['coordinates of westernmost','P1335'],
             ['highest point','P610'],
             ['weather history','P4150'],
             ['head of government','P6'],
             ['population','P1080'],
             ['male population','P1540'],
             ['female population','P1539'],
             ['located in time zone','P421'],
             ['median income','P3529'],
             ['owner of','P1830'],
             ['follows','P155'],
             ['significant event','P793'],
             ['area','P2046'],
             ['postal code','P281'],
             ['locator map image','P242'],
             ['location map','P1943'],
             ['flag','P163'],
             ['collage image','P2716'],
             ['history of topic','P2184']]
}


@app.route('/', methods=['GET', 'POST'])
def index():
    selected_option = None
    contents = None
    if request.method == 'POST':
        selected_option = request.form.get('selected_option')
        if selected_option in dropdown_options:
            contents = dropdown_options[selected_option]

    return render_template('iii.html', options=dropdown_options.keys(), selected_option=selected_option, contents=contents)

if __name__ == '__main__':
    app.run(debug=True)
